services:
  checkmk:
    image: "checkmk/check-mk-raw:2.4.0-latest"
    container_name: "checkmk"
    environment:
      - CMK_PASSWORD=$CMK_PASSWORD
      - OMD_SITE=monitoring
      - TZ=Europe/Berlin
    volumes:
      - monitoring:/omd/sites
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ports:
      - "5000:5000"
      - "8000:8000"
    restart: always
    networks:
      - core

volumes:
  monitoring:

networks:
  core:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.60.0/24
          gateway: 192.168.60.1
